[package]
name = "formatter-xml"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
distiller-core = { path = "../distiller-core" }

[dev-dependencies]
