run:
  timeout: 5m
  go: '1.21'
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional useful linters
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - misspell
    - unconvert
    - unparam
    - dogsled
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gofumpt
    - gomnd
    - goprintffuncname
    - lll
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - rowserrcheck
    - exportloopref
    - whitespace
    - wsl

  disable:
    - typecheck  # Can be unreliable in some contexts

linters-settings:
  gocyclo:
    min-complexity: 15
    
  golint:
    min-confidence: 0.8
    
  lll:
    line-length: 120
    
  gofmt:
    simplify: true
    
  goimports:
    local-prefixes: github.com/janreges/ai-distiller
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  misspell:
    locale: US
    
  nakedret:
    max-func-lines: 30
    
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
    
  unparam:
    check-exported: false
    
  unused:
    check-exported: false
    
  gosec:
    excludes:
      - G404  # Random number generation
      - G304  # File path injection (we handle files)
      
  nestif:
    min-complexity: 4
    
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
        ignored-numbers: 0,1,2,8,10,16,24,32,64,100,1024

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gomnd
        
    # Exclude linters for generated files
    - path: \.pb\.go$
      linters:
        - gofmt
        - goimports
        - golint
        - govet
        
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
      
    # Exclude some gosec rules that are not applicable
    - linters:
        - gosec
      text: "G110:"  # Potential DoS vulnerability via decompression bomb
      
    # Allow long lines in embedding directives
    - linters:
        - lll
      source: "^//go:embed"

  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 3
  
  # Show only new issues created after git revision
  new-from-rev: ""