run:
  timeout: 5m
  go: '1.22'

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional useful linters
    - gocyclo
    - gofmt
    - goimports
    - revive        # replaces deprecated golint
    - gosec
    - misspell
    - unconvert
    - unparam
    - dogsled
    - dupl
    - goconst
    - gocritic
    - godot
    - gofumpt
    - mnd          # replaces deprecated gomnd
    - goprintffuncname
    - lll
    - nakedret
    - nestif
    - prealloc
    - whitespace
    - wsl
    - bodyclose
    - noctx
    - rowserrcheck
    - stylecheck
    - tparallel

  disable:
    - gochecknoglobals
    - gochecknoinits
    - testpackage
    - wrapcheck
    - paralleltest
    - exhaustive
    - exhaustivestruct
    - goerr113
    - nlreturn
    - gci
    - gocognit
    - godox
    - funlen

linters-settings:
  gocyclo:
    min-complexity: 15
    
  lll:
    line-length: 140
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  misspell:
    locale: US
    
  nakedret:
    max-func-lines: 30
    
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
    
  unparam:
    check-exported: false
    
  unused:
    check-exported: false
    
  gosec:
    excludes:
      - G404  # Random number generation
      - G304  # File path injection (we handle files)
      
  nestif:
    min-complexity: 4
    
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '8'
      - '10'
      - '16'
      - '24'
      - '32'
      - '64'
      - '100'
      - '1024'

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        
    # Allow unused in test utilities
    - path: _test\.go
      linters:
        - unused
        
    # Exclude known issues in generated files
    - path: \.pb\.go$
      linters:
        - gofmt
        - goimports
        - gocritic
        
    # Allow init functions in main packages
    - path: ^cmd/
      linters:
        - gochecknoinits
        
    # Allow globals in version package
    - path: internal/version/version\.go
      linters:
        - gochecknoglobals
        
    # Allow line length in test data files
    - path: test-data/
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0