[package]
name = "lang-swift"
version = "0.1.0"
edition = "2021"

[dependencies]
distiller-core = { path = "../distiller-core" }
tree-sitter = "0.24"
tree-sitter-swift = "0.6"
parking_lot = "0.12"

[dev-dependencies]
insta = { version = "1.34", features = ["yaml"] }
