[package]
name = "lang-java"
version = "0.1.0"
edition = "2024"

[dependencies]
distiller-core = { path = "../distiller-core" }
tree-sitter = "0.25"
tree-sitter-java = "0.23"
parking_lot = "0.12"

[dev-dependencies]
insta = { version = "1.34", features = ["yaml"] }
