[package]
name = "lang-c"
version = "0.1.0"
edition = "2021"

[dependencies]
distiller-core = { path = "../distiller-core" }
tree-sitter = "0.25"
tree-sitter-c = "0.23"
parking_lot = "0.12"
anyhow = "1.0"
